odpi/egeria-connector-jdbc

.github/workflows/merge.yml
build.gradle
settings.gradle

Corrects references to old repo names in gradle/build definitions

Correct references to repo name

---

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/JdbcIntegrationConnector.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/ffdc/JdbcConnectorAuditCode.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ColumnTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/SchemaTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/TableTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/ViewTransfer.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/Jdbc.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveColumn.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveSchema.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveTable.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasRemoveView.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateColumn.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateDatabase.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateSchema.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateTable.java
jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/requests/OmasUpdateView.java

Signed-off-by: Liviu Constantin Popa <liviu-constantin.popa@ing.com>

Add ability to transfer databases that do not support catalogs

---

jdbc-integration-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/JdbcIntegrationConnector.java

Error message format fix

---

.github/dependabot.yml
.github/workflows/merge.yml
.github/workflows/release.yml
Dockerfile
LICENSE-Docker.txt

Builds an aggregate container with
- Base egeria - version aligned with gradle dependencies
- Resource & integration jdbc connectors (from this repo)
- Optional additional libraries. As example postgres is added (BSD-2 simplified license)

Build Docker container

---

Dockerfile

* Ensures VERSION available in docker build environment

#36 Ensure VERSION set in environment

---

.github/workflows/merge.yml
.github/workflows/release.yml

#36 pass build args to docker correctly

---

.github/workflows/merge.yml
.github/workflows/release.yml

#36 quote base image name

---

.github/workflows/merge.yml
.github/workflows/release.yml

#36 fix cr/lf in workflows

---

.github/workflows/merge.yml
.github/workflows/release.yml
Dockerfile
gradle.properties

#36 update to docker/merge build

---

.github/workflows/merge.yml
.github/workflows/release.yml

#36 retrieve connector version from integrator connector project

---

.github/workflows/merge.yml
.github/workflows/release.yml
.github/workflows/stale.yml
build.gradle

Resolve outstanding PRs & refine gradle definitions in prep for release

Prep for release

---

build.gradle

Updates version to 1.0 for release.
No branch- tag only, then will increment version to 1.1-SNAPSHOT

#2 update version to 1.0 for release

---

build.gradle

Fixes to gradle to support release process

Additional build fixes for correct maven artifacts

---

.github/workflows/release.yml

#2 disable parallelism for publishing

---

build.gradle

#2 fix gradle signing properties

---

build.gradle

#2 Ensure project name specified in pom to match gradle project name

---

.github/workflows/merge.yml
.github/workflows/release.yml

- Fix incorrect image name which could lead to overwrite of core image
- correct image version parsing due to dependency changes

Fix incorrect container name & egeria version parsing

---

.github/workflows/merge.yml
.github/workflows/release.yml

Correct typo in image name

---

.github/workflows/merge.yml
build.gradle

port merge action fix + new dev snapshot

1.2-snapshot

---

.github/workflows/merge.yml
.github/workflows/release.yml
Dockerfile

Release 1.1

---

.github/workflows/merge.yml
.github/workflows/release.yml
Dockerfile

Fixes implemented while working on release 1.1

Release fixes
